version: "3.8"

services:
  postgres-docker-oltp:
    container_name: postgres-docker-oltp
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: casino-oltp
    ports:
      - "5432:5432"
    volumes:
      - ./1.2-generated-data-in-csvs:/csvs
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d casino-oltp -h localhost" ]
      interval: 2s
      timeout: 1s
      retries: 5